### ISSUE TITLE
Fail with 'Fatal error: spawn ENOENT' when executing multiple targets

### ISSUE THREAD

**Issue by AndreasPresthammer** [spatools/grunt-xdt#1]
```
xdt: {
    First: {},
    Second: {}
}
```

A configuration containing more than one tasks will fail when you run both tasks.

Error: Fatal error: spawn ENOENT

I can run either one in isolation.
grunt xdt:first
grunt xdt:second
works fine. But when I run 'grunt xdt' is fails.

**Comment by SomaticIT** [comment]
Thank you for reporting this issue.
I fixed this in version 0.1.1 which is published to npm.
So you can update your dependencies now to resolve your error.

**Comment by AndreasPresthammer** [comment]
Excellent, thanks!
